# Copyright (C) 2025 Gray Matter Logic
# License LGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Advanced LIMS",
    "summary": "LOINC, stages, teams, instruments, batches and order workflow for LIMS",
    "version": "18.0.1.0.0",
    "license": "LGPL-3",
    "category": "Laboratories",
    "author": "Gray Matter Logic, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/connector-lims",
    "depends": ["lims", "mail", "resource"],
    "data": [
        "data/ir_sequence.xml",
        "data/mail_message_subtype.xml",
        "data/lims_stage.xml",
        "data/lims_team.xml",
        "data/loinc.code.csv",
        "data/res_partner.xml",
        "data/lims_method.xml",
        "data/lims_test.xml",
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "views/res_config_settings.xml",
        "views/loinc_code.xml",
        "views/lims_stage.xml",
        "views/lims_tag.xml",
        "views/res_partner.xml",
        "views/lims_batch.xml",
        "views/lims_category.xml",
        "views/lims_instrument.xml",
        "views/lims_result.xml",
        "views/lims_test.xml",
        "views/lims_test_result.xml",
        "views/lims_method.xml",
        "views/lims_sample.xml",
        "views/lims_analysis.xml",
        "views/lims_team.xml",
        "views/product_template.xml",
        "views/menu.xml",
    ],
    "demo": [
        "demo/res_partner.xml",
        "demo/lims_instrument.xml",
        "demo/lims_team.xml",
        "demo/product_template.xml",
        "demo/lims_method.xml",
        "demo/lims_test.xml",
        "demo/lims_test_result.xml",
        "demo/lims_sample.xml",
        "demo/lims_batch.xml",
        "demo/lims_analysis.xml",
        "demo/lims_result.xml",
    ],
    "application": False,
    "installable": True,
    "development_status": "Beta",
    "maintainers": ["max3903"],
    "assets": {
        "web.assets_backend": [
            "lims_advanced/static/src/scss/team_dashboard.scss",
        ]
    },
}
